config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]
  resources :attractions

  root "/", controller: "static", action: "index"

  get "/signin", controller: "sessions", action: "new"
  post "/signin", controller: "sessions", action: "create"
  delete "/signout", controller: "sessions", action: "destroy"

  post "/attractions/:id", controller: "attractions", action: "take_ride"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  belongs_to :attraction

  def take_ride
    messages = []
    if self.user.tickets && self.user.tickets < self.attraction.tickets
      messages << "You do not have enough tickets to ride the #{self.attraction.name}."
    end

    if self.user.height && self.user.height < self.attraction.min_height
      messages << "You are not tall enough to ride the #{attraction.name}."
    end

    unless messages.empty?
      messages.insert(0, "Sorry.")
      return messages.join(" ")
    else
      update_user_attributes
    end
  end

  private
  def update_user_attributes
    self.user.tickets -= self.attraction.tickets
    self.user.happiness += self.attraction.happiness_rating
    self.user.nausea += self.attraction.nausea_rating
    self.user.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rides
  has_many :attractions, through: :rides

  def mood
    self.happiness && self.nausea && self.happiness > self.nausea ? "happy" : "sad"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :is_admin?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def is_authenticated?
    if !logged_in?
      flash[:message] = 'You must be logged in to view this content'
      redirect_to root_path
    end
  end

  def is_admin?
    current_user && current_user.admin
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :is_authenticated?, except: [:index]
  before_action :can_modify?, except: [:index, :show]

  def index
    @attractions = Attraction.order(:name)
  end

  def show
    @attraction = Attraction.find(params[:id])
  end

  def take_ride
    @attraction = Attraction.find(params[:id])
    @ride = Ride.new(user: current_user, attraction: @attraction)
    messages = @ride.take_ride

    if messages.class != String
      @ride.save
      flash[:message] = "Thanks for riding the #{@attraction.name}!"
    else
      flash[:message] = messages
    end

    redirect_to user_path(current_user)
  end

  def new
    @attraction = Attraction.new
  end

  def create
    @attraction = Attraction.new(attraction_params)

    if @attraction.save
      redirect_to attraction_path(@attraction)
    else
      redirect_to new_attraction_path
    end
  end

  def edit
    @attraction = Attraction.find(params[:id])
  end

  def update
    @attraction = Attraction.find(params[:id])

    if @attraction.update(attraction_params)
      redirect_to attraction_path(@attraction)
    else
      redirect_to edit_attraction_path
    end
  end

  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy
    redirect_to attractions_path
  end

  private

  def attraction_params
    params.require(:attraction).permit(:name, :nausea_rating, :happiness_rating, :min_height, :tickets)
  end

  def can_modify?
    redirect_to attractions_path unless is_admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, except: [:destroy]
  def new

  end

  def create
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = "Invalid combination"
      redirect_to signin_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def redirect_if_logged_in
    if logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user!, only: [:show]
  before_action :is_authenticated?, only: [:show]
  before_action :can_only_view_yourself?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def show

  end

  private

  def set_user!
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :nausea, :happiness, :tickets, :height, :admin)
  end

  def can_only_view_yourself?
    unless is_admin? || current_user.id == params[:id].to_i
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="ui violet inverted menu">
  <div class="header item">
    Amusement Park on Rails 5
  </div>
  <%= link_to "Home", root_path, class: "item" %>
  <%= link_to "Attractions", attractions_path, class: "item" %>
  <% unless logged_in? %>
      <%= link_to "Sign Up", new_user_path, class: "item" %>
      <%= link_to "Sign In", signin_path, class: "item" %>
  <% else %>
      <%= link_to "My account", user_path(current_user), class: "item" %>
      <%= link_to "Log Out", signout_path, method: "delete", class: "item" %>
  <% end %>
</div>

app/views/attractions/_card.html.erb
<div class="ui raised link card">
  <div class="content">
    <div class="header"><%= attraction.name %></div>
    <div class="meta">
      <span class="category"><i class="icon ticket"></i> <%= pluralize(attraction.tickets, "ticket") %></span>
    </div>
    <div class="description">
      <ul>
        <li>Nausea Rating: <%= attraction.nausea_rating %></li>
        <li>Happiness Rating: <%= attraction.happiness_rating %></li>
        <li>Min. Height: <%= attraction.nausea_rating %></li>
      </ul>
    </div>
  </div>
  <div class="extra content">
    <%= link_to "Go on #{attraction.name}", attraction_path(attraction), class: "fluid ui orange button" unless is_admin? %>
    <%= link_to "Show #{attraction.name}", attraction_path(attraction), class: "fluid ui primary button" if is_admin? %>
  </div>
</div>

app/views/attractions/_form.html.erb
<%= form_for @attraction, html: {class: "ui form"} do |f| %>
    <div class="five wide field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="five wide field">
      <%= f.label :nausea_rating %>
      <%= f.number_field :nausea_rating %>
    </div>
    <div class="five wide field">
      <%= f.label :happiness_rating %>
      <%= f.number_field :happiness_rating %>
    </div>
    <div class="five wide field">
      <%= f.label :min_height %>
      <%= f.number_field :min_height %>
    </div>
    <div class="five wide field">
      <%= f.label :tickets %>
      <%= f.number_field :tickets %>
    </div>
    <%= f.submit class: "ui primary submit button" %>
<% end %>

app/views/attractions/edit.html.erb
<h1 class="ui dividing header">Edit Attraction</h1>

<%= render partial: "form", object: @attraction %>

app/views/attractions/index.html.erb
<% if is_admin? %>
    <div class="ui segment">
      <%= link_to "New Attraction", new_attraction_path, class: "ui teal button" %>
    </div>
<% end %>
<div class="ui three cards">
  <% @attractions.each do |attraction| %>
      <%= render partial: "card", locals: {attraction: attraction} %>
  <% end %>
</div>

app/views/attractions/new.html.erb
<h1 class="ui dividing header">New Attraction</h1>

<%= render partial: "form", object: @attraction %>

app/views/attractions/show.html.erb
<h1 class="ui dividing header">Attraction</h1>

<div class="ui card">
  <div class="content">
    <div class="header">Ride Info</div>
  </div>
  <div class="content">
    <div class="meta">Name</div>
    <div class="description">
      <i class="user circle icon"></i><%= @attraction.name %>
    </div>
    <div class="meta">Nausea Rating</div>
    <div class="description">
      <i class="frown icon"></i><%= @attraction.nausea_rating %>
    </div>
    <div class="meta">Happiness Rating</div>
    <div class="description">
      <i class="smile icon"></i><%= @attraction.happiness_rating %>
    </div>
    <div class="meta">Min. Height</div>
    <div class="description">
      <i class="long arrow up icon"></i><%= @attraction.min_height %>
    </div>
    <div class="meta">Tickets</div>
    <div class="description">
      <i class="ticket icon"></i><%= @attraction.tickets %>
    </div>
  </div>
  <div class="extra content">
    <%= button_to "Go on this ride", attraction_path(@attraction), class: "fluid ui primary button" unless is_admin?%>
    <%= link_to "Edit Attraction", edit_attraction_path(@attraction), class: "fluid ui pink button", style: "margin-bottom:10px" if is_admin? %>
    <%= link_to "Delete Attraction", attraction_path(@attraction), class: "fluid ui red button", method: :delete if is_admin? %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmusementPark5</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="main ui container">
  <header>
    <%= render partial: "header" %>
  </header>
  <div class="ui segment">
    <% if flash[:message] %>
        <div class="ui red inverted segment"><%= flash[:message] %></div>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/users/new.html.erb
<h1 class="ui dividing header">Sign Up</h1>

<%= form_for @user, url: users_path, html: {class: "ui form"} do |f| %>
    <div class="five wide field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="five wide field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="five wide field">
      <%= f.label :nausea %>
      <%= f.number_field :nausea %>
    </div>
    <div class="five wide field">
      <%= f.label :happiness %>
      <%= f.number_field :happiness %>
    </div>
    <div class="five wide field">
      <%= f.label :height %>
      <%= f.number_field :height %>
    </div>
    <div class="five wide field">
      <%= f.label :tickets %>
      <%= f.number_field :tickets %>
    </div>
    <div class="inline field">
      <%= f.label :admin %>
      <%= f.check_box :admin, class: "ui checkbox" %>
    </div>
    <%= f.submit "Create User", class: "ui primary submit button" %>
<% end %>

app/views/users/show.html.erb
<h1 class="ui dividing header">User Page</h1>

<div class="ui card">
  <div class="content">
    <% if is_admin? %>
        <span class="ui red left floated ribbon label">ADMIN</span>
    <% end %>
    <div class="header">Your information</div>
  </div>
  <div class="content">
    <div class="meta">Name:</div>
    <div class="description">
      <i class="user circle icon"></i><%= @user.name %>
    </div>
    <div class="meta">Nausea:</div>
    <div class="description">
      <i class="frown icon"></i><%= @user.nausea %>
    </div>
    <div class="meta">Happiness:</div>
    <div class="description">
      <i class="smile icon"></i><%= @user.happiness %>
    </div>
    <div class="meta">Mood:</div>
    <div class="description">
      <i class="meh icon"></i><%= @user.mood %>
    </div>
    <div class="meta">Height:</div>
    <div class="description">
      <i class="long arrow up icon"></i><%= @user.height %>
    </div>
    <div class="meta">Tickets:</div>
    <div class="description">
      <i class="ticket icon"></i><%= @user.tickets %>
    </div>
  </div>
  <div class="extra content">
    <%= link_to "See attractions", attractions_path, class: "ui primary button" %>
  </div>
</div>